### PR TITLE
Ignore docs/tag generated by vim

### PR DESCRIPTION
**Pull request by sharils**
This change is [Reviewable](https://reviewable.io/reviews/rhysd/devdocs.vim/7)

### CODE REVIEW

**Comment by rhysd** [comment]
Why this change is needed? I'm not pathogen user, so please describe the reason.

**Comment by sharils** [comment]
Hi @rhysd - Sure! I was confused by Pathogen and I just fix the PR subject. It should be ignored simply because `:helptags` generates them and that's annoying to users who use `git submodule` to manage their plugins like me. Because those user would see changes in submodule directory, and there is no way to ignore them. :( I'd really appreciate it if this is accepted. My justification for this would be since it's derived data, it shouldn't be committed anyway.

**Comment by daGrevis** [comment]
You can use global `.gitignore`. https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by rhysd** [comment]
@sharils I understood your use case. I actually did not consider the case where this plugin is managed via git submodules. But it means that all the plugins you're using need to put `.gitignore` and it looks not so feasible. You need to explain your use case in each plugins like this PR. How about using global gitignore as @daGrevis suggested? I feel it would be better.

**Comment by sharils** [comment]
OK, thanks. I'll just take that approach.

**Pull request closed without merging**
